version: 2.0
jobs:
  build:
    docker:
      - image: intel/oneapi-basekit
    steps:
      - checkout
      - run:
          command: |
            cd src
            . /opt/intel/inteloneapi/setvars.sh
            make
