name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: intel/oneapi-basekitw
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          cd src
	  . /opt/intel/inteloneapi/setvars.sh
          make
